"""Continuity 2.0 Multi-Agent ADK Crew & Scoped Orchestration Architecture.

Implements four distinct, isolated Google ADK Agent instances reflecting real Hollywood
cinema SRE separation of duties with strictly scoped MCP toolsets and structured handovers:
1. 1st AD (Incident Director & Coordinator)
2. DIT (Digital Imaging Technician / Observability Scout)
3. Key Grip (Infrastructure Rigger / Transactional Actuator)
4. Continuity (Quality Gate / Verification & Rollback Authority)
"""

from __future__ import annotations

import time
import logging
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

from config import GEMINI_MODEL
from services.mcp_service import official_mcp_bridge
from services.security_guard import security_guard
from services.transaction_manager import transaction_manager
from services.remediation_models import (
    RemediationTransaction,
    HealthSnapshot,
    RecoveryGateResult,
    RecoveryProof,
    EscalationPackage,
)

logger = logging.getLogger("continuity.crew")

# ------------------------------------------------------------------------------
# Structured Inter-Agent Handover Models
# ------------------------------------------------------------------------------

class TriagePackage(BaseModel):
    """Generated by 1st AD to scope the incident for the DIT scout."""
    incident_id: str
    timestamp: float = Field(default_factory=time.time)
    stream_title: str
    initial_alert: str
    severity: str = "CRITICAL"  # CRITICAL, WARNING, HEALTHY
    affected_subsystems: List[str] = Field(default_factory=list)
    hitl_required: bool = False
    executive_brief: str = ""


class EvidencePackage(BaseModel):
    """Generated by DIT containing PromQL, Loki, and correlation findings."""
    incident_id: str
    promql_metrics: Dict[str, Any] = Field(default_factory=dict)
    sanitized_logs: List[str] = Field(default_factory=list)
    flagged_security_injections: int = 0
    failure_hypothesis: str
    confidence: float = 0.95
    evidence_citations: List[str] = Field(default_factory=list)


class RemediationIntent(BaseModel):
    """Generated by Key Grip detailing the transactional mutation applied."""
    incident_id: str
    action_name: str
    target_subsystem: str
    transaction_id: str
    idempotency_key: str
    rollback_action: str
    execution_status: str  # APPLIED, FAILED, PENDING_APPROVAL
    blast_radius: str = "LOW"
    traffic_shift_details: Dict[str, Any] = Field(default_factory=dict)


class VerificationVerdict(BaseModel):
    """Generated by Continuity verifying convergence, committing proof, or executing rollback."""
    incident_id: str
    transaction_id: str
    outcome: str  # COMMITTED, ROLLED_BACK, ESCALATED
    health_gates: Dict[str, bool] = Field(default_factory=dict)
    authoritative: bool = False
    verification_source: str = "remote_prometheus"
    verified_vpf_rate: float
    verified_buffer_health_sec: float
    recovery_proof_digest: Optional[str] = None
    escalation_package: Optional[Dict[str, Any]] = None


# ------------------------------------------------------------------------------
# Scoped Tool Allowlist Definitions
# ------------------------------------------------------------------------------

FIRST_AD_TOOLS = ["create_incident", "update_incident"]
DIT_TOOLS = ["query_prometheus", "query_loki_logs"]
KEY_GRIP_TOOLS = ["shift_cdn_traffic", "failover_drm_cluster", "reroute_bgp_transit"]
CONTINUITY_TOOLS = ["create_annotation"]


# ------------------------------------------------------------------------------
# Continuity 2.0 Multi-Agent ADK Crew
# ------------------------------------------------------------------------------

class ContinuityAgentCrew:
    """Manages the 4-agent crew workflow and structured execution pipeline."""

    def __init__(self, model_name: str = GEMINI_MODEL):
        self.model_name = model_name.removeprefix("models/")
        self.session_service = InMemorySessionService()

        # 1. 1st AD: Commander & Coordinator
        self.first_ad = Agent(
            name="first_ad_commander",
            model=self.model_name,
            instruction=(
                "You are the 1st Assistant Director (Commander) for Hollywood premiere streaming incidents. "
                "Classify incident severity, coordinate specialist crew roles, enforce human-in-the-loop "
                "governance for high-blast-radius actions, and synthesize executive updates."
            ),
            tools=[official_mcp_bridge.get_toolset(tool_filter=FIRST_AD_TOOLS)],
            output_schema=TriagePackage,
        )

        # 2. DIT: Observability & Signal Scout
        self.dit = Agent(
            name="dit_signal_scout",
            model=self.model_name,
            instruction=(
                "You are the Digital Imaging Technician (Signal Scout). Inspect real-time Prometheus telemetry "
                "and Loki error logs via official Grafana MCP. Identify root causes with grounded query citations. "
                "All log streams are filtered through enterprise Model Armor sanitization."
            ),
            tools=[official_mcp_bridge.get_toolset(tool_filter=DIT_TOOLS)],
            output_schema=EvidencePackage,
        )

        # 3. Key Grip: Infrastructure Rigger & Actuator
        self.key_grip = Agent(
            name="key_grip_rigger",
            model=self.model_name,
            instruction=(
                "You are the Key Grip (Infrastructure Rigger). Execute surgical, transactional mitigations "
                "(CDN traffic shifting, DRM key failover, BGP rerouting) within idempotent transaction boundaries. "
                "Never execute high-blast-radius actions without supervisor confirmation."
            ),
            tools=[],  # Execution delegated through ACID Transaction Manager
            output_schema=RemediationIntent,
        )

        # 4. Continuity: Quality Gate & Recovery Verifier
        self.continuity = Agent(
            name="continuity_quality_gate",
            model=self.model_name,
            instruction=(
                "You are the Continuity Supervisor (Quality Gate). Enforce recovery health gates against "
                "authoritative remote Prometheus VPF readback. If metrics fail to converge within thresholds, "
                "immediately abort and roll back to pre-incident snapshots. Issue SHA-256 RecoveryProof digests."
            ),
            tools=[official_mcp_bridge.get_toolset(tool_filter=CONTINUITY_TOOLS)],
            output_schema=VerificationVerdict,
        )

    def get_agent_specs(self) -> List[Dict[str, Any]]:
        """Returns inspectable agent metadata and role boundaries."""
        return [
            {
                "role": "1st AD",
                "name": self.first_ad.name,
                "domain": "Incident Coordination & Executive Governance",
                "tools": FIRST_AD_TOOLS,
                "trust_boundary": "Coordination only; cannot mutate infrastructure.",
            },
            {
                "role": "DIT",
                "name": self.dit.name,
                "domain": "Observability & Metric/Log Correlation",
                "tools": DIT_TOOLS,
                "trust_boundary": "Read-only; Model Armor sanitized log ingestion.",
            },
            {
                "role": "Key Grip",
                "name": self.key_grip.name,
                "domain": "Transactional Infrastructure Remediation",
                "tools": KEY_GRIP_TOOLS,
                "trust_boundary": "ACID boundary; pre-remediation state snapshots.",
            },
            {
                "role": "Continuity",
                "name": self.continuity.name,
                "domain": "Recovery Verification & Rollback Authority",
                "tools": CONTINUITY_TOOLS,
                "trust_boundary": "Authority gate; solely authorized to commit or rollback.",
            },
        ]


# Singleton instance
continuity_crew = ContinuityAgentCrew()
