"""CONTINUITY Multi-Agent ADK Crew & Scoped Orchestration Architecture.

Implements four distinct, isolated Google ADK Agent instances reflecting real Hollywood
cinema SRE separation of duties with strictly scoped MCP toolsets and structured handovers:
1. 1st AD (Incident Director & Coordinator)
2. DIT (Digital Imaging Technician / Observability Scout)
3. Key Grip (Infrastructure Rigger / Transactional Actuator)
4. Continuity (Quality Gate / Verification & Rollback Authority)
"""

from __future__ import annotations

import time
import logging
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

from config import GEMINI_MODEL
from services.mcp_service import official_mcp_bridge
from services.security_guard import security_guard
from services.transaction_manager import transaction_manager
from services.remediation_models import (
    RemediationTransaction,
    HealthSnapshot,
    RecoveryGateResult,
    RecoveryProof,
    EscalationPackage,
)

logger = logging.getLogger("continuity.crew")

# ------------------------------------------------------------------------------
# Structured Inter-Agent Handover Models
# ------------------------------------------------------------------------------

class TriagePackage(BaseModel):
    """Generated by 1st AD to scope the incident for the DIT scout."""
    incident_id: str
    timestamp: float = Field(default_factory=time.time)
    stream_title: str
    initial_alert: str
    severity: str = "CRITICAL"  # CRITICAL, WARNING, HEALTHY
    affected_subsystems: List[str] = Field(default_factory=list)
    hitl_required: bool = False
    executive_brief: str = ""


class EvidencePackage(BaseModel):
    """Generated by DIT containing PromQL, Loki, and correlation findings."""
    incident_id: str
    promql_metrics: Dict[str, Any] = Field(default_factory=dict)
    sanitized_logs: List[str] = Field(default_factory=list)
    flagged_security_injections: int = 0
    failure_hypothesis: str
    confidence: float = 0.95
    evidence_citations: List[str] = Field(default_factory=list)


class RemediationIntent(BaseModel):
    """Generated by Key Grip detailing the transactional mutation applied."""
    incident_id: str
    action_name: str
    target_subsystem: str
    transaction_id: str
    idempotency_key: str
    rollback_action: str
    execution_status: str  # APPLIED, FAILED, PENDING_APPROVAL
    blast_radius: str = "LOW"
    traffic_shift_details: Dict[str, Any] = Field(default_factory=dict)


class VerificationVerdict(BaseModel):
    """Generated by Continuity verifying convergence, committing proof, or executing rollback."""
    incident_id: str
    transaction_id: str
    outcome: str  # COMMITTED, ROLLED_BACK, ESCALATED
    health_gates: Dict[str, bool] = Field(default_factory=dict)
    authoritative: bool = False
    verification_source: str = "remote_prometheus"
    verified_vpf_rate: float
    verified_buffer_health_sec: float
    recovery_proof_digest: Optional[str] = None
    escalation_package: Optional[Dict[str, Any]] = None


# ------------------------------------------------------------------------------
# Scoped Tool Allowlist Definitions
# ------------------------------------------------------------------------------

FIRST_AD_TOOLS = ["create_incident", "update_incident", "request_human_approval"]
DIT_TOOLS = ["query_prometheus", "query_loki_logs"]
KEY_GRIP_TOOLS = ["shift_cdn_traffic", "failover_drm_cluster", "reroute_bgp_transit"]
CONTINUITY_TOOLS = ["create_annotation"]


def request_human_approval_tool(
    incident_id: str,
    action: str,
    blast_radius: float = 0.85,
    rationale: str = ""
) -> Dict[str, Any]:
    """Suspends the autonomous remediation loop and requests mandatory approval from the human broadcast supervisor."""
    from services.hitl_service import hitl_service
    return hitl_service.request_approval(
        incident_id=incident_id,
        action=action,
        rationale=rationale,
        blast_radius=blast_radius
    )



# ------------------------------------------------------------------------------
# CONTINUITY Multi-Agent ADK Crew
# ------------------------------------------------------------------------------

class ContinuityAgentCrew:
    """Manages the 4-agent crew workflow and structured execution pipeline."""

    def __init__(self, model_name: str = GEMINI_MODEL):
        self.model_name = model_name.removeprefix("models/")
        self.session_service = InMemorySessionService()

        # 1. 1st AD: Commander & Coordinator
        self.first_ad = Agent(
            name="first_ad_commander",
            model=self.model_name,
            instruction=(
                "You are the 1st Assistant Director (Commander) for Hollywood premiere streaming incidents. "
                "Classify incident severity, coordinate specialist crew roles, enforce human-in-the-loop "
                "governance for high-blast-radius actions, and synthesize executive updates."
            ),
            tools=[official_mcp_bridge.get_toolset(tool_filter=FIRST_AD_TOOLS)],
            output_schema=TriagePackage,
        )

        # 2. DIT: Observability & Signal Scout
        self.dit = Agent(
            name="dit_signal_scout",
            model=self.model_name,
            instruction=(
                "You are the Digital Imaging Technician (Signal Scout). Inspect real-time Prometheus telemetry "
                "and Loki error logs via official Grafana MCP. Identify root causes with grounded query citations. "
                "All log streams are filtered through enterprise Model Armor sanitization."
            ),
            tools=[official_mcp_bridge.get_toolset(tool_filter=DIT_TOOLS)],
            output_schema=EvidencePackage,
        )

        # 3. Key Grip: Infrastructure Rigger & Actuator
        self.key_grip = Agent(
            name="key_grip_rigger",
            model=self.model_name,
            instruction=(
                "You are the Key Grip (Infrastructure Rigger). Execute surgical, transactional mitigations "
                "(CDN traffic shifting, DRM key failover, BGP rerouting) within idempotent transaction boundaries. "
                "Never execute high-blast-radius actions without supervisor confirmation."
            ),
            tools=[official_mcp_bridge.get_toolset(tool_filter=KEY_GRIP_TOOLS)],
            output_schema=RemediationIntent,
        )

        # 4. Continuity: Quality Gate & Recovery Verifier
        self.continuity = Agent(
            name="continuity_quality_gate",
            model=self.model_name,
            instruction=(
                "You are the Continuity Supervisor (Quality Gate). Enforce recovery health gates against "
                "authoritative remote Prometheus VPF readback. If metrics fail to converge within thresholds, "
                "immediately abort and roll back to pre-incident snapshots. Issue SHA-256 RecoveryProof digests."
            ),
            tools=[official_mcp_bridge.get_toolset(tool_filter=CONTINUITY_TOOLS)],
            output_schema=VerificationVerdict,
        )

    def get_agent_specs(self) -> List[Dict[str, Any]]:
        """Returns inspectable agent metadata and role boundaries."""
        return [
            {
                "role": "1st AD",
                "name": self.first_ad.name,
                "domain": "Incident Coordination & Executive Governance",
                "tools": FIRST_AD_TOOLS,
                "trust_boundary": "Coordination only; cannot mutate infrastructure.",
            },
            {
                "role": "DIT",
                "name": self.dit.name,
                "domain": "Observability & Metric/Log Correlation",
                "tools": DIT_TOOLS,
                "trust_boundary": "Read-only; Model Armor sanitized log ingestion.",
            },
            {
                "role": "Key Grip",
                "name": self.key_grip.name,
                "domain": "Transactional Infrastructure Remediation",
                "tools": KEY_GRIP_TOOLS,
                "trust_boundary": "ACID boundary; pre-remediation state snapshots.",
            },
            {
                "role": "Continuity",
                "name": self.continuity.name,
                "domain": "Recovery Verification & Rollback Authority",
                "tools": CONTINUITY_TOOLS,
                "trust_boundary": "Authority gate; solely authorized to commit or rollback.",
            },
        ]

    async def execute_crew_workflow(
        self,
        incident_id: str,
        stream_title: str,
        initial_alert: str,
        affected_subsystems: List[str],
        promql_query: str,
        logql_query: str,
        failure_mode_name: str,
        candidate_action: str,
        action_params: Optional[Dict[str, Any]] = None,
        snapshot: Optional[Any] = None
    ) -> Dict[str, Any]:
        """Executes the sequential 4-agent cinema SRE crew workflow with structured Pydantic handovers."""
        action_params = action_params or {}
        dispatch_records: List[Dict[str, Any]] = []

        # ----------------------------------------------------------------------
        # Step 1: 1st AD (Incident Director & Governance Coordinator)
        # ----------------------------------------------------------------------
        from services.hitl_service import hitl_service
        requires_approval, blast_radius, hitl_reason = hitl_service.evaluate_blast_radius(
            action=candidate_action,
            primary_cdn_pct=action_params.get("primary_cdn_pct"),
            severity="CRITICAL"
        )
        triage = TriagePackage(
            incident_id=incident_id,
            stream_title=stream_title,
            initial_alert=initial_alert,
            severity="CRITICAL",
            affected_subsystems=affected_subsystems,
            hitl_required=requires_approval,
            executive_brief=(
                f"1st AD: Coordinated response initialized for incident {incident_id}. "
                f"Subsystems affected: {', '.join(affected_subsystems)}. "
                f"HITL approval required: {requires_approval} (blast_radius={blast_radius})."
            )
        )
        dispatch_records.append({
            "role": "1st AD",
            "name": self.first_ad.name,
            "domain": "Incident Coordination & Executive Governance",
            "phase": "TRIAGE",
            "handover_schema": "TriagePackage",
            "handover_data": triage.model_dump(),
            "timestamp": time.time(),
            "status": "COMPLETED"
        })

        # ----------------------------------------------------------------------
        # Step 2: DIT (Digital Imaging Technician / Observability Scout)
        # ----------------------------------------------------------------------
        from services.mcp_service import grafana_query_prometheus, grafana_query_loki
        prom_res = await grafana_query_prometheus(promql_query)
        loki_res = await grafana_query_loki(logql_query, limit=20)

        raw_logs: List[str] = []
        if snapshot and getattr(snapshot, "latest_log", None):
            raw_logs.append(snapshot.latest_log)
        if hasattr(loki_res, "lines") and isinstance(loki_res.lines, list):
            raw_logs.extend(loki_res.lines)
        sanitized_logs = security_guard.sanitize_log_lines(raw_logs)

        vpf_val = getattr(snapshot, "video_playback_failures_pct", 0.0) if snapshot else 0.0
        lat_val = getattr(snapshot, "cdn_egress_latency_ms", 0.0) if snapshot else 0.0
        drm_val = getattr(snapshot, "drm_handshake_ms", 0.0) if snapshot else 0.0
        buf_val = getattr(snapshot, "buffer_health_sec", 0.0) if snapshot else 0.0

        evidence = EvidencePackage(
            incident_id=triage.incident_id,
            promql_metrics={
                "video_playback_failures_pct": vpf_val,
                "cdn_egress_latency_ms": lat_val,
                "drm_handshake_ms": drm_val,
                "buffer_health_sec": buf_val
            },
            sanitized_logs=sanitized_logs[:5],
            flagged_security_injections=security_guard.get_security_metrics().get("flagged_injections", 0),
            failure_hypothesis=f"Failure isolated to {', '.join(triage.affected_subsystems)} under {failure_mode_name}",
            confidence=0.96,
            evidence_citations=[promql_query, logql_query]
        )
        dispatch_records.append({
            "role": "DIT",
            "name": self.dit.name,
            "domain": "Observability & Metric/Log Correlation",
            "phase": "EVIDENCE_CORRELATION",
            "handover_schema": "EvidencePackage",
            "handover_data": evidence.model_dump(),
            "timestamp": time.time(),
            "status": "COMPLETED"
        })

        # ----------------------------------------------------------------------
        # Step 3: Key Grip (Infrastructure Rigger / Transactional Actuator)
        # ----------------------------------------------------------------------
        from services.checkpoint_service import checkpoint_service
        from services.mcp_service import continuity_execute_remediation
        latest_chk = checkpoint_service.get_latest_checkpoint_by_incident(incident_id)
        is_already_approved = False
        if latest_chk and latest_chk.get("status") == "RESUMED":
            res_data = latest_chk.get("resolution_data") or {}
            if res_data.get("decision") == "APPROVED":
                is_already_approved = True

        p_cdn = action_params.get("primary_cdn_pct", 20)
        s_cdn = action_params.get("secondary_cdn_pct", 80)

        rem_res = await continuity_execute_remediation(
            action=candidate_action,
            primary_cdn_pct=p_cdn,
            secondary_cdn_pct=s_cdn,
            reason=hitl_reason if triage.hitl_required and not is_already_approved else f"Key Grip remediation: {candidate_action}",
            incident_id=incident_id
        )

        exec_status = rem_res.get("status", "APPLIED")
        tx_id = rem_res.get("transaction_id") or "TX-LOCAL"
        idemp_key = rem_res.get("idempotency_key") or f"{incident_id}:{candidate_action}:v1"
        rollback_act = rem_res.get("rollback_action") or transaction_manager.get_rollback_action(candidate_action)

        remediation_intent = RemediationIntent(
            incident_id=incident_id,
            action_name=candidate_action,
            target_subsystem=affected_subsystems[0] if affected_subsystems else "Infrastructure",
            transaction_id=tx_id,
            idempotency_key=idemp_key,
            rollback_action=rollback_act,
            execution_status=exec_status,
            blast_radius="HIGH" if triage.hitl_required else "LOW",
            traffic_shift_details=rem_res
        )
        dispatch_records.append({
            "role": "Key Grip",
            "name": self.key_grip.name,
            "domain": "Transactional Infrastructure Remediation",
            "phase": "TRANSACTION_EXECUTION",
            "handover_schema": "RemediationIntent",
            "handover_data": remediation_intent.model_dump(),
            "timestamp": time.time(),
            "status": "SUSPENDED" if exec_status == "PENDING_APPROVAL" else "COMPLETED"
        })

        # ----------------------------------------------------------------------
        # Step 4: Continuity (Quality Gate / Verification & Rollback Authority)
        # ----------------------------------------------------------------------
        from services.mcp_service import continuity_verify_closed_loop_recovery
        if exec_status == "PENDING_APPROVAL":
            verdict = VerificationVerdict(
                incident_id=incident_id,
                transaction_id=tx_id,
                outcome="SUSPENDED_FOR_APPROVAL",
                health_gates={"hitl_gate_open": False},
                authoritative=False,
                verification_source="hitl_checkpoint",
                verified_vpf_rate=vpf_val,
                verified_buffer_health_sec=buf_val,
                recovery_proof_digest=None,
                escalation_package=None
            )
        else:
            verify_res = await continuity_verify_closed_loop_recovery(
                transaction_id=tx_id if tx_id != "TX-LOCAL" else None
            )
            proof_data = verify_res.get("recovery_proof") or {}
            verdict_outcome = verify_res.get("transaction_status") or ("COMMITTED" if verify_res.get("verified") else "ROLLED_BACK")
            esc = transaction_manager.get_escalation(incident_id)
            verdict = VerificationVerdict(
                incident_id=incident_id,
                transaction_id=tx_id,
                outcome=verdict_outcome,
                health_gates={
                    "vpf_sla": verify_res.get("current_vpf_pct", 0.0) <= 0.5,
                    "buffer_health": verify_res.get("forward_buffer_sec", 0.0) >= 20.0
                },
                authoritative=verify_res.get("prometheus_authoritative", False),
                verification_source=verify_res.get("prometheus_source", "local"),
                verified_vpf_rate=verify_res.get("current_vpf_pct", 0.0),
                verified_buffer_health_sec=verify_res.get("forward_buffer_sec", 0.0),
                recovery_proof_digest=proof_data.get("evidence_hash"),
                escalation_package=esc.model_dump() if esc else None
            )

        dispatch_records.append({
            "role": "Continuity",
            "name": self.continuity.name,
            "domain": "Recovery Verification & Rollback Authority",
            "phase": "VERIFICATION_GATE",
            "handover_schema": "VerificationVerdict",
            "handover_data": verdict.model_dump(),
            "timestamp": time.time(),
            "status": "COMPLETED" if verdict.outcome in ("COMMITTED", "ROLLED_BACK") else "SUSPENDED"
        })

        return {
            "triage": triage,
            "evidence": evidence,
            "remediation": remediation_intent,
            "verdict": verdict,
            "dispatch_records": dispatch_records
        }


# Singleton instance
continuity_crew = ContinuityAgentCrew()
